### ISSUE TITLE
Can't open repository

### ISSUE THREAD

**Issue by uetchy** [yoshitakame/open-gitup#1]
I've tried `open-gitup` on latest version of Atom but failed.

I solved this issue by changing [this line](https://github.com/yoshitakame/open-gitup/blob/master/lib/open-gitup.coffee#L24) to `exec("open -a GitUp.app '#{path}'")`.

Could you update this package with above?

**Comment by yo7** [comment]
I updated the package.

Honestly, I made this package quite before and I no longer use either Atom and GitUp. I think it has many bugs other than that... But anyway, thank you for trying this package!
